language: python
python:
    - "2.6"
    - "2.7"
    - "3.1"
    - "3.2"
    - "3.3"
    - "pypy"

before_install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
    - pip install pep8
    - pep8 $TRAVIS_BUILD_DIR/samples/*.py
    - pep8 $TRAVIS_BUILD_DIR/samples/tools/*.py

install:
    - python setup.py bdist_egg
    - pip install -e file://$TRAVIS_BUILD_DIR

script:
    nosetests


